Repository emscripten-core/emscripten, pull requests merged in 2018-08, with the labels that each got.

#6942 Update list of automatically enabled WebGL extensions to latest
  src/library_gl.js
Labels: GL

#5581 Multithreading 14/N: OFFSCREEN_FRAMEBUFFER
  site/source/docs/api_reference/html5.h.rst
  src/library_browser.js
  src/library_gl.js
  src/library_glfw.js
  src/library_glut.js
  src/library_html5.js
  src/library_sdl.js
  src/settings.js
  src/struct_info.json
  system/include/emscripten/html5.h
  tests/test_browser.py
  tests/webgl_draw_triangle.c
Labels: GL, multithreading

#7051 Add a pthreads-offscreencanvas test with gl *only* in a pthread
  tests/gl_only_in_pthread.cpp
  tests/test_browser.py
Labels: GL, multithreading, offscreencanvas
