Repository emscripten-core/emscripten, pull requests merged in 2018-10, with the labels that each got.

#7190 Fix WebGL enableExtensionsByDefault
  src/library_html5.js
Labels: GL

#7265 Add note about MAIN_THREAD_EM_ASM in singlethreaded, emterpreter and …
  system/include/emscripten/em_asm.h
Labels: multithreading

#7356 fix_full_es2_without_enable_extensions_by_default
  src/library_gl.js
  tests/test_browser.py
  tests/test_core.py
  tests/webgl_draw_triangle.c
Labels: GL

#7317 Add an assertion for OFFSCREENCANVAS_SUPPORT without GL
  src/library_pthread.js
Labels: GL

#7264 fix_void_func_proxying
  src/jsifier.js
Labels: multithreading

#7261 Fix timedwait cp
  system/lib/libc/musl/src/thread/__timedwait.c
  system/lib/pthread/library_pthread.c
  system/lib/pthreads.symbols
Labels: multithreading

#6201 Multithreading 29/N: Backproxying
  emscripten-version.txt
  src/library_pthread.js
  src/library_pthread_stub.js
  src/preamble.js
  src/struct_info.json
  system/include/emscripten/html5.h
  system/include/emscripten/threading.h
  system/lib/pthread/library_pthread.c
  tests/pthread/test_pthread_run_script.cpp
  tests/test_browser.py
  tests/test_other.py
  tools/gen_struct_info.py
Labels: HTML5 API, multithreading

#7191 Add a workaround for Safari 9 ARM iOS right shift by non-immediate zero JIT bug
  emcc.py
  emscripten.py
  src/preamble.js
  src/settings.js
  tests/test_other.py
Labels: iOS

#7401 Fixed a hang in eglGetConfigs.
  src/library_egl.js
Labels: EGL
