Repository emscripten-core/emscripten, pull requests merged in 2018-11, with the labels that each got.

#6194 Multithreading 25/N: fix_fetch_deadlock
  system/lib/fetch/emscripten_fetch.cpp
Labels: multithreading

#6199 Multithreading 28/N: Drop debug prints in ASMFS and Fetch API
  system/lib/fetch/asmfs.cpp
  system/lib/fetch/emscripten_fetch.cpp
Labels: multithreading

#6193 Multithreading 24/N: Proxy GLUT functions to main thread
  src/library_glut.js
Labels: multithreading

#6198 Multithreading 27/N: Store Wasm Module also in sync Wasm compilation
  src/preamble.js
  src/pthread-main.js
  tests/test_browser.py
Labels: multithreading

#6195 Multithreading 26/N: emscripten_thread_sleep
  system/include/emscripten/threading.h
  system/lib/pthread/library_pthread.c
  tests/pthread/emscripten_thread_sleep.c
  tests/test_browser.py
Labels: multithreading

#6243 Multithreading 33/N: WebGL proxying preliminaries
  src/library_gl.js
  tests/test_other.py
Labels: GL, multithreading

#7447 Add the missing needed signatures to proxy WebGL 1 and 2 functions
  system/include/emscripten/threading.h
  system/lib/pthread/library_pthread.c
Labels: GL, multithreading

#7257 manual_html5_event_unloading
  src/library_html5.js
  system/include/emscripten/html5.h
  tests/test_html5.c
  tests/test_other.py
Labels: HTML5 API

#6202 Multithreading 30/N: HTML5 Event Backproxying
  emscripten-version.txt
  src/library_html5.js
  src/postamble.js
  src/pthread-main.js
  src/struct_info.json
  system/include/emscripten/html5.h
  tests/html5_callbacks_on_calling_thread.c
  tests/html5_event_callback_in_two_threads.c
  tests/test_browser.py
  tests/test_interactive.py
Labels: HTML5 API, multithreading

#7459 workaround_old_chromium_webgl_bug
  emcc.py
  src/library_gl.js
  src/settings.js
  tests/test_browser.py
  tests/webgl_draw_triangle_with_uniform_color.c
Labels: GL

#7461 Adds not operator to val.
  src/embind/emval.js
  system/include/emscripten/val.h
  tests/embind/test_val.cpp
  tests/embind/test_val.out
Labels: embind

#7452 Minify asmjs module imports
  emcc.py
  emscripten.py
  src/settings.js
  tests/gen_many_js_functions.py
  tests/test_other.py
  tools/minified_js_name_generator.py
Labels: performance

#6254 Multithreading 34/34: OffscreenCanvas + proxied Canvas support
  emscripten-version.txt
  site/source/docs/api_reference/html5.h.rst
  src/deps_info.json
  src/library_browser.js
  src/library_gl.js
  src/library_html5.js
  src/library_pthread.js
  src/struct_info.json
  system/include/emscripten/html5.h
  system/include/emscripten/threading.h
  system/lib/gl.symbols
  system/lib/gl/gl.c
  system/lib/gl/webgl1.c
  system/lib/gl/webgl1.h
  system/lib/gl/webgl1_ext.h
  system/lib/gl/webgl2.c
  system/lib/gl/webgl2.h
  system/lib/gl/webgl2_ext.h
  system/lib/pthread/library_pthread.c
  tests/canvas_animate_resize.cpp
  tests/canvas_animate_resize_shell.html
  tests/gl_in_proxy_pthread.cpp
  tests/gl_in_pthread.cpp
  tests/gl_in_two_pthreads.cpp
  tests/resize_offscreencanvas_from_main_thread.cpp
  tests/test_browser.py
  tests/test_interactive.py
  tests/test_other.py
  tools/system_libs.py
Labels: GL, multithreading, performance
