Repository emscripten-core/emscripten, pull requests merged in 2019-12, with the labels that each got.

#9932 Fix GL_HALF_FLOAT validation error on vertexAttribPointer for WebGL2
  src/library_webgl.js
Labels: GL

#9920 Remove extraneous checks for page scrolling
  src/library_html5.js
Labels: HTML5 API

#9918 GL_UNSIGNED_SHORT_5_6_5_REV
  src/library_webgl2.js
  tests/test_browser.py
  tests/webgl2_invalid_teximage2d_type.cpp
Labels: GL

#9938 Micro optimize webgl
  src/library_webgl.js
  src/library_webgl2.js
  tests/other/metadce/hello_world_fastcomp_O3_MAIN_MODULE.sent
  tests/test_other.py
Labels: GL

#9921 Optimize accesses to domElement.getBoundingClientRect()
  src/library_html5.js
  tests/other/metadce/hello_world_fastcomp_O3_MAIN_MODULE.sent
  tests/test_other.py
Labels: HTML5 API

#9937 Add setting fields to control which browser versions to support
  emcc.py
  src/library_html5.js
  src/library_webgl.js
  src/parseTools.js
  src/settings.js
  tests/test_other.py
Labels: GL, HTML5 API

#9969 Use MIN_X_VERSION in emscripten_get_now().
  src/library.js
Labels: HTML5 API

#9946 Disable deprecated find event target behavior
  ChangeLog.md
  emcc.py
  src/library_html5.js
  src/settings.js
  tests/canvas_size_proxy.c
  tests/emscripten_set_canvas_element_size.c
  tests/keydown_preventdefault_proxy.cpp
  tests/other/metadce/hello_world_fastcomp_O3_MAIN_MODULE.sent
  tests/test_browser.py
  tests/test_other.py
  tests/webgl2_objects.cpp
  tests/webgl2_pbo.cpp
  tests/webgl2_ubos.cpp
  tests/webgl_create_context.cpp
  tests/webgl_create_context2.cpp
  tests/webgl_shader_source_length.cpp
  tests/webgl_with_closure.cpp
Labels: HTML5 API

#9953 Pool calls to WebGL 1 functions glUniform*iv()
  src/library_webgl.js
Labels: GL

#9987 Remove timestamp value from HTML5
  ChangeLog.md
  site/source/docs/api_reference/html5.h.rst
  src/library_html5.js
  src/struct_info.json
  system/include/emscripten/html5.h
Labels: HTML5 API

#9919 Remove supportsWebGL2EntryPoints
  src/library_webgl.js
  src/library_webgl2.js
  tests/test_browser.py
  tests/test_other.py
Labels: GL

#7672 full_posix_sockets
  .circleci/config.yml
  embuilder.py
  site/source/docs/porting/index.rst
  site/source/docs/porting/networking.rst
  src/deps_info.json
  src/library.js
  src/library_syscall.js
  src/settings.js
  system/include/emscripten/posix_socket.h
  system/lib/libc-sockets.symbols
  system/lib/websocket/websocket_to_posix_socket.cpp
  tests/test_sockets.py
  tests/websocket/nodejs_websocket_echo_server.js
  tests/websocket/tcp_echo_client.cpp
  tests/websocket/tcp_echo_server.py
  tests/websocket/tcp_in_two_threads.cpp
  tests/websocket/test_websocket_send.c
  tools/shared.py
  tools/system_libs.py
  tools/websocket_to_posix_proxy/CMakeLists.txt
  tools/websocket_to_posix_proxy/src/main.cpp
  tools/websocket_to_posix_proxy/src/posix_sockets.h
  tools/websocket_to_posix_proxy/src/sha1.cpp
  tools/websocket_to_posix_proxy/src/sha1.h
  tools/websocket_to_posix_proxy/src/socket_registry.cpp
  tools/websocket_to_posix_proxy/src/socket_registry.h
  tools/websocket_to_posix_proxy/src/threads.h
  tools/websocket_to_posix_proxy/src/websocket_to_posix_proxy.cpp
  tools/websocket_to_posix_proxy/src/websocket_to_posix_proxy.h
Labels: multithreading, networking

#9968 Remove old html5 api support
  src/library_html5.js
  tests/test_browser.py
Labels: HTML5 API

#9972 Generalize yielding execution back to browser
  site/source/docs/api_reference/html5.h.rst
  src/library_browser.js
  src/library_glut.js
  src/library_html5.js
  src/library_pthread.js
  src/postamble.js
  src/preamble.js
  src/worker.js
  system/include/emscripten/html5.h
  tests/browser/test_emscripten_unwind_to_js_event_loop.c
  tests/test_browser.py
Labels: HTML5 API

#10032 Misc threads fixes
  src/library_pthread.js
  src/modules.js
Labels: multithreading

#10041 Remove FS.createStandardStreams in pthreads
  src/worker.js
Labels: filesystem, multithreading

#10042 Remove preamble function Module['applyStackValues']()
  emcc.py
  src/library_pthread.js
  src/preamble.js
  src/support.js
  src/worker.js
Labels: multithreading

#10020 MAX_WEBGL_VERSION
  emcc.py
  site/source/docs/optimizing/Optimizing-WebGL.rst
  site/source/docs/porting/multimedia_and_graphics/OpenGL-support.rst
  src/library_browser.js
  src/library_egl.js
  src/library_glemu.js
  src/library_webgl.js
  src/library_webgl2.js
  src/modules.js
  src/settings.js
  system/lib/gl/gl.c
  tests/minimal_webgl/webgl.c
  tests/test_browser.py
  tests/test_other.py
  tools/system_libs.py
Labels: GL

#10097 Remove workaround for Firefox 66 and older for WebGL 2
  src/library_webgl.js
Labels: GL

#10102 Replace uses of LEGACY_VM_SUPPORT with the new MIN_xxx_VERSION fields
  emcc.py
  src/library_html5.js
  src/runtime_math.js
  tests/test_other.py
Labels: code size

#10096 Use GL enum integer values instead of GL enum names to save space
  src/library_egl.js
  src/library_glemu.js
  src/library_html5.js
  src/library_webgl.js
  src/library_webgl2.js
  src/runtime_stack_check.js
  tests/minimal_webgl/library_js.js
Labels: Desktop OpenGL emulation, GL, code size

#10100 Remove remains of function Pointer_stringify()
  src/modules.js
  src/runtime_strings.js
Labels: code size

#10104 Micro-optimize WebAssembly Table creation
  src/preamble_minimal.js
Labels: code size
