Repository emscripten-core/emscripten, pull requests merged in 2019-05, with the labels that each got.

#8530 Build gl separately for OFFSCREEN_FRAMEBUFFER
  embuilder.py
  system/lib/gl/webgl1.c
  system/lib/gl/webgl1.h
  system/lib/gl/webgl2.c
  tests/test_browser.py
  tools/system_libs.py
Labels: GL, multithreading

#8541 Rename legacy GL emulation related sloppy GL extension lookup functions
  system/lib/gl/gl.c
  system/lib/gl/webgl1.c
  system/lib/gl/webgl2.c
Labels: Desktop OpenGL emulation, GL

#8286 Return detached threads to the pool
  src/library_pthread.js
  tests/pthread/test_std_thread_detach.cpp
  tests/test_browser.py
Labels: multithreading

#8628 Do not set mediump precision on vertex shaders
  src/library_glemu.js
Labels: Desktop OpenGL emulation

#8552 Not all DeviceMotionEvent fields are necessarily supported
  site/source/docs/api_reference/html5.h.rst
  src/library_html5.js
  src/struct_info.json
  system/include/emscripten/html5.h
  tests/test_html5.c
Labels: HTML5 API

#8685 Accept the python version 2.7.10 that comes out of the box on macOS
  site/source/docs/building_from_source/toolchain_what_is_needed.rst
  tools/shared.py
Labels: OSX
