Repository emscripten-core/emscripten, pull requests merged in 2019-01, with the labels that each got.

#7814 library_html5.js: only check for .commit() if OFFSCRENCANVAS_SUPPORT is on
  src/library_html5.js
Labels: GL

#7829 gl_code_size_optimizations
  src/library_browser.js
  src/library_gl.js
  src/settings.js
Labels: GL

#7665 Improve ASMFS support
  emcc.py
  src/library_asmfs.js
  src/preamble.js
  system/include/emscripten/asmfs.h
  system/include/emscripten/fetch.h
  system/lib/fetch/asmfs.cpp
  system/lib/fetch/emscripten_fetch.cpp
Labels: filesystem, multithreading

#7842 library_glemu
  emscripten-version.txt
  src/closure-externs.js
  src/library_gl.js
  src/library_glemu.js
  src/modules.js
  system/lib/gl/gl.c
  tools/system_libs.py
Labels: Desktop OpenGL emulation, GL

#7670 Add Emscripten WebSockets API
  src/library_websocket.js
  src/settings.js
  system/include/emscripten/websocket.h
  tests/websocket/websocket.c
Labels: multithreading, networking

#7858 EGL attributes improvements
  src/library_egl.js
  tools/shared.py
Labels: EGL, GL

#7889 no_module_asmglobalarg
  emscripten.py
  tests/optimizer/test-function-eliminator-double-parsed-correctly-output.js
  tests/optimizer/test-function-eliminator-double-parsed-correctly.js
  tests/optimizer/test-function-eliminator-replace-array-value-output.js
  tests/optimizer/test-function-eliminator-replace-array-value-with-hash-info.js
  tests/optimizer/test-function-eliminator-replace-array-value.js
  tests/optimizer/test-function-eliminator-replace-function-call-output-with-hash-info.js
  tests/optimizer/test-function-eliminator-replace-function-call-output.js
  tests/optimizer/test-function-eliminator-replace-function-call-two-passes-output.js
  tests/optimizer/test-function-eliminator-replace-function-call-with-hash-info.js
  tests/optimizer/test-function-eliminator-replace-function-call.js
  tests/optimizer/test-function-eliminator-replace-object-value-assignment-output.js
  tests/optimizer/test-function-eliminator-replace-object-value-assignment-with-hash-info.js
  tests/optimizer/test-function-eliminator-replace-object-value-assignment.js
  tests/optimizer/test-function-eliminator-replace-variable-value-output.js
  tests/optimizer/test-function-eliminator-replace-variable-value-with-hash-info.js
  tests/optimizer/test-function-eliminator-replace-variable-value.js
  tests/optimizer/test-function-eliminator-simple-output.js
  tests/optimizer/test-function-eliminator-simple-with-hash-info.js
  tests/optimizer/test-function-eliminator-simple.js
  tests/optimizer/test-function-eliminator-variable-clash-output.js
  tests/optimizer/test-function-eliminator-variable-clash-with-hash-info.js
  tests/optimizer/test-function-eliminator-variable-clash.js
  tools/distill_asm.py
Labels: code size

#7891 avoid_dummy_atinit_push
  emscripten.py
Labels: code size

#7890 micro_optimize_declare_asm_module_exports
  emscripten.py
Labels: code size

#7887 avoid_enlargememory
  src/support.js
Labels: code size

#7863 expand_bare_minimum_html5_api_functions
  site/source/docs/api_reference/html5.h.rst
  src/library_browser.js
  src/library_html5.js
  src/settings.js
  system/include/emscripten/html5.h
  tests/emscripten_console_log.c
  tests/emscripten_console_log_pre.js
  tests/emscripten_performance_now.c
  tests/emscripten_request_animation_frame.c
  tests/emscripten_request_animation_frame_loop.c
  tests/emscripten_set_immediate.c
  tests/emscripten_set_immediate_loop.c
  tests/emscripten_set_interval.c
  tests/emscripten_set_timeout.c
  tests/emscripten_set_timeout_loop.c
  tests/emscripten_throw_number.c
  tests/emscripten_throw_number_pre.js
  tests/emscripten_throw_string.c
  tests/emscripten_throw_string_pre.js
  tests/test_browser.py
  tests/test_other.py
Labels: code size

#7834 no_binary_data_serialization_into_utf8
  src/preamble.js
Labels: code size

#7885 micro_optimize_memcpy_big
  emscripten-version.txt
  src/library.js
  system/lib/libc/emscripten_memcpy.c
Labels: code size

#7899 optimize_no_support_errno
  embuilder.py
  tests/test_sanity.py
  tools/system_libs.py
Labels: code size

#7902 JSEvents_diet
  src/library_html5.js
  tests/test_other.py
Labels: code size

#7882 emscripten_wegbl_get_context_attributes and powerPreference
  site/source/docs/api_reference/html5.h.rst
  src/library_html5.js
  src/struct_info.json
  system/include/emscripten/html5.h
  tests/gl_textures.cpp
  tests/test_html5_fullscreen.c
  tests/webgl2.cpp
  tests/webgl2_garbage_free_entrypoints.cpp
Labels: GL

#7900 less_pointer_stringify
  site/source/docs/api_reference/preamble.js.rst
  src/Fetch.js
  src/library_html5.js
  src/preamble.js
  src/runtime_stack_trace.js
  src/runtime_strings.js
  system/lib/fetch/emscripten_fetch.cpp
  tools/shared.py
Labels: code size

#7886 Fast unrolled memcpy and memset
  site/source/docs/api_reference/html5.h.rst
  src/library.js
  src/settings.js
Labels: code size

#7910 remove_jsevents_auto_deps
  src/library_html5.js
Labels: code size

#7911 no_special_abortOnCannotGrowMemory
  emscripten.py
  src/library.js
  src/preamble.js
  tests/test_core.py
  tests/test_other.py
Labels: code size

#7915 Assorted variable declaration fixes
  src/library_gl.js
  src/library_openal.js
Labels: GL, OpenAL

#7922 Remove unused setDynamicTop() function
  emscripten.py
Labels: code size

#7925 Remove some more silly Module.wasm* things
  src/jsifier.js
  src/library_pthread.js
  src/preamble.js
  src/worker.js
Labels: code size

#7937 Remove unused asm.js variable undef
  emscripten.py
Labels: code size

#7938 Move setThrew() function over to JS library
  emscripten.py
  src/library.js
  tests/test_other.py
  tools/shared.py
Labels: code size

#7940 collapse_redundant_vars_in_asm
  emscripten.py
  tests/test_other.py
Labels: code size

#7931 memory_growth_to_js_library
  emscripten.py
  src/library.js
  src/preamble.js
  src/settings.js
  tests/core/test_memorygrowth_3.c
  tests/test_core.py
  tests/test_other.py
Labels: code size

#7924 Remove fake SSE support
  .circleci/config.yml
  emcc.py
  system/include/SSE/emmintrin.h
  system/include/SSE/immintrin.h
  system/include/SSE/pmmintrin.h
  system/include/SSE/smmintrin.h
  system/include/SSE/tmmintrin.h
  system/include/SSE/x86intrin.h
  system/include/SSE/xmmintrin.h
  tests/benchmark_sse.h
  tests/benchmark_sse1.cpp
  tests/benchmark_sse1.py
  tests/benchmark_sse2.cpp
  tests/benchmark_sse2.py
  tests/core/test_simd10.c
  tests/core/test_simd11.c
  tests/core/test_simd12.c
  tests/core/test_simd13.c
  tests/core/test_simd14.c
  tests/core/test_simd15.c
  tests/core/test_simd16.c
  tests/core/test_simd3.c
  tests/core/test_simd4.c
  tests/core/test_simd6.c
  tests/core/test_simd7.c
  tests/core/test_simd8.c
  tests/core/test_simd9.c
  tests/core/test_simd_dyncall.cpp
  tests/core/test_simd_set_epi64x.c
  tests/test_core.py
  tests/test_interactive.py
  tests/test_sse1.cpp
  tests/test_sse1_full.cpp
  tests/test_sse2_full.cpp
  tests/test_sse3_full.cpp
  tests/test_sse4_1_full.cpp
  tests/test_sse_full.h
  tests/test_ssse3_full.cpp
Labels: SIMD

#7947 Fix build of SINGLE_FILE + ENVIRONMENT=web + Closure combined together (#7933)
  emcc.py
  src/base64Utils.js
  src/library.js
  tests/test_browser.py
Labels: code size

#7939 Manual DCE asm primitives
  emscripten.py
  src/settings.js
Labels: code size

#7942 group_global_initializers
  emscripten.py
  tests/test_other.py
Labels: code size

#7959 Remove docs for GL state cache that never landed
  site/source/docs/optimizing/Optimizing-WebGL.rst
Labels: GL
