Repository emscripten-core/emscripten, pull requests merged in 2019-02, with the labels that each got.

#7970 Remove some unneeded code from ccall, and optimize it
  src/preamble.js
Labels: code size

#7966 Optimize webgl code size
  src/library_gl.js
  src/library_html5.js
  src/runtime_strings.js
Labels: GL, code size

#7996 Fix WebGL context attribute handling and Chrome workaround
  src/library_gl.js
  src/library_html5.js
Labels: GL

#7991 Fix GL library Closure support with uniform upload workaround
  src/library_gl.js
  tests/test_browser.py
Labels: GL

#7992 Fix asmfs library to not use EMSCRIPTEN_KEEPALIVE, those are not needed
  system/lib/fetch/asmfs.cpp
Labels: code size

#7990 Optimize code size of UTF8ToString()
  src/runtime_strings.js
Labels: code size, performance

#7985 Implement proper support for emscripten_is_webgl_context_lost()
  src/library_html5.js
Labels: GL

#7978 Optimize JS library aliases
  src/library.js
  src/library_html5.js
  src/library_pthread_stub.js
  src/library_signals.js
  src/library_syscall.js
  src/modules.js
Labels: code size, performance

#7998 Remove uses of deprecated canvas resize functions
  site/source/api_items.py
  site/source/docs/api_reference/emscripten.h.rst
  site/source/docs/api_reference/html5.h.rst
  src/library_sdl.js
  tests/gl_textures.cpp
  tests/sdl2_canvas_size.c
  tests/sdl_canvas.c
  tests/sdl_canvas_alpha.c
  tests/sdl_fullscreen_samecanvassize.c
  tests/sdl_togglefullscreen.c
  tests/sdl_wm_togglefullscreen.c
  tests/test_html5_fullscreen.c
  tests/test_html5_mouse.c
  tests/test_html5_pointerlockerror.c
  tests/webgl2_garbage_free_entrypoints.cpp
  tests/webgl2_objects.cpp
  tests/webgl_shader_source_length.cpp
  tests/webgl_with_closure.cpp
Labels: HTML5 API

#7989 Make asmLibraryArg a local variable "var asmLibraryArg = ...;"
  emscripten.py
  src/support.js
  tests/optimizer/applyDCEGraphRemovals-output.js
  tests/optimizer/applyDCEGraphRemovals.js
  tests/optimizer/applyImportAndExportNameChanges-output.js
  tests/optimizer/applyImportAndExportNameChanges.js
  tests/optimizer/emitDCEGraph.js
  tests/optimizer/emitDCEGraph2.js
  tests/optimizer/emitDCEGraph3.js
  tests/optimizer/emitDCEGraph4.js
  tests/optimizer/emitDCEGraph5.js
  tests/optimizer/test-function-eliminator-double-parsed-correctly-output.js
  tests/optimizer/test-function-eliminator-double-parsed-correctly.js
  tests/optimizer/test-function-eliminator-replace-array-value-output.js
  tests/optimizer/test-function-eliminator-replace-array-value-with-hash-info.js
  tests/optimizer/test-function-eliminator-replace-array-value.js
  tests/optimizer/test-function-eliminator-replace-function-call-output-with-hash-info.js
  tests/optimizer/test-function-eliminator-replace-function-call-output.js
  tests/optimizer/test-function-eliminator-replace-function-call-two-passes-output.js
  tests/optimizer/test-function-eliminator-replace-function-call-with-hash-info.js
  tests/optimizer/test-function-eliminator-replace-function-call.js
  tests/optimizer/test-function-eliminator-replace-object-value-assignment-output.js
  tests/optimizer/test-function-eliminator-replace-object-value-assignment-with-hash-info.js
  tests/optimizer/test-function-eliminator-replace-object-value-assignment.js
  tests/optimizer/test-function-eliminator-replace-variable-value-output.js
  tests/optimizer/test-function-eliminator-replace-variable-value-with-hash-info.js
  tests/optimizer/test-function-eliminator-replace-variable-value.js
  tests/optimizer/test-function-eliminator-simple-output.js
  tests/optimizer/test-function-eliminator-simple-with-hash-info.js
  tests/optimizer/test-function-eliminator-simple.js
  tests/optimizer/test-function-eliminator-variable-clash-output.js
  tests/optimizer/test-function-eliminator-variable-clash-with-hash-info.js
  tests/optimizer/test-function-eliminator-variable-clash.js
  tests/test_other.py
  tools/distill_asm.py
  tools/js-optimizer.js
Labels: code size

#8002 dont_force_filesystem_in_pthreads
  emcc.py
Labels: filesystem, multithreading

#7923 Add -s MINIMAL_RUNTIME=1 option.
  emcc.py
  emscripten.py
  src/deps_info.json
  src/jsifier.js
  src/library.js
  src/library_gl.js
  src/library_html5.js
  src/library_pthread_stub.js
  src/library_syscall.js
  src/modules.js
  src/postamble_minimal.js
  src/preamble.js
  src/preamble_minimal.js
  src/runtime_safe_heap.js
  src/runtime_stack_check.js
  src/runtime_strings.js
  src/settings.js
  src/shell_minimal.js
  src/shell_minimal_runtime.html
  tests/declare_asm_module_exports.cpp
  tests/minimal_webgl/library_js.js
  tests/minimal_webgl/main.cpp
  tests/minimal_webgl/moon.png
  tests/minimal_webgl/webgl.c
  tests/minimal_webgl/webgl.h
  tests/optimizer/minimal-runtime-emitDCEGraph-output.js
  tests/optimizer/minimal-runtime-emitDCEGraph.js
  tests/small_hello_world.c
  tests/test_browser.py
  tests/test_core.py
  tests/test_global_initializer.cpp
  tests/test_other.py
  tools/distill_asm.py
  tools/hacky_postprocess_around_closure_limitations.py
  tools/js-optimizer.js
  tools/preprocessor.js
  tools/separate_asm.py
  tools/shared.py
Labels: code size

#8009 Fix deps for emscripten_webgl_destroy_context
  src/deps_info.json
Labels: GL, multithreading

#8008 no_commit_in_chrome
  tests/test_browser.py
Labels: GL, offscreencanvas

#8006 fix_emscripten_is_webgl_context_lost
  site/source/docs/api_reference/html5.h.rst
  system/include/emscripten/html5.h
Labels: GL

#7993 Streamline WebGL context creation
  src/library_browser.js
  src/library_gl.js
  tests/test_browser.py
  tests/test_other.py
Labels: GL, code size

#8012 Fix MEMFS use in ENVIRONMENT=web + closure. Fixes #8010
  src/library_fs.js
  src/library_syscall.js
  src/library_tty.js
  tests/test_browser.py
  tests/write_file.cpp
Labels: code size, filesystem

#8011 Remove deprecated function Pointer_stringify()
  site/source/docs/api_reference/preamble.js.rst
  src/fetch-worker.js
  src/modules.js
  src/runtime_strings.js
  third_party/jni/emjvm.js
  tools/webidl_binder.py
Labels: code size

#8015 Optimize code size of invoke wrappers
  src/library.js
  src/library_signals.js
  src/settings.js
  tests/test_core.py
  tools/shared.py
Labels: code size

#7667 Add support for MODULARIZE with USE_PTHREADS
  emcc.py
  src/library_pthread.js
  src/modules.js
  src/parseTools.js
  src/preamble.js
  src/shell.js
  src/shell_pthreads.js
  src/worker.js
  tests/shell_that_launches_modularize.html
  tests/test_browser.py
  tools/preprocessor.js
  tools/shared.py
Labels: multithreading

#8026 Enable abort() C function to work in MINIMAL_RUNTIME
  src/library.js
Labels: code size

#8025 Optimize C runtime exit() function: in MINIMAL_RUNTIME exit will throw
  src/library.js
Labels: code size

#8024 optimize_long_exception_msg_string
  src/parseTools.js
  tests/test_core.py
Labels: code size

#7977 -s DISABLE_DEPRECATED_FIND_EVENT_TARGET_BEHAVIOR
  ChangeLog.md
  src/library_html5.js
  src/settings.js
  src/struct_info.json
  system/include/emscripten/html5.h
  tests/canvas_animate_resize.cpp
  tests/gl_in_mainthread_after_pthread.cpp
  tests/gl_in_proxy_pthread.cpp
  tests/gl_in_pthread.cpp
  tests/gl_in_two_pthreads.cpp
  tests/gl_only_in_pthread.cpp
  tests/gl_textures.cpp
  tests/html5_callbacks_on_calling_thread.c
  tests/preinitialized_webgl_context.cpp
  tests/resize_offscreencanvas_from_main_thread.cpp
  tests/test_browser.py
  tests/test_html5.c
  tests/test_html5_fullscreen.c
  tests/test_html5_mouse.c
  tests/test_html5_pointerlockerror.c
  tests/test_interactive.py
  tests/test_keyboard_codes.c
  tests/test_other.py
  tests/webgl2.cpp
  tests/webgl2_backwards_compatibility_emulation.cpp
  tests/webgl2_garbage_free_entrypoints.cpp
  tests/webgl_color_buffer_readpixels.cpp
  tests/webgl_create_context.cpp
  tests/webgl_create_context2.cpp
  tests/webgl_destroy_context.cpp
Labels: HTML5 API, code size

#8023 Optimize stub pthreads functions to run inside asm module.
  embuilder.py
  src/compiler.js
  src/library_pthread_stub.js
  system/lib/asmjs_pthreads.symbols
  system/lib/pthread/library_pthread_asmjs.c
  system/lib/pthread/library_pthread_stub.c
  system/lib/pthreads.symbols
  system/lib/stub_pthreads.symbols
  tests/test_other.py
  tools/system_libs.py
Labels: code size, multithreading, performance

#8037 blitOffscreenFramebuffer fixes
  src/library_gl.js
  tests/test_browser.py
  tests/webgl_offscreen_framebuffer_swap_with_bad_state.c
Labels: GL

#8050 dce_abortOnCannotGrowMemory
  src/library.js
  tests/test_core.py
Labels: code size

#8049 Use response files when invoking emar
  emar.py
  tools/shared.py
Labels: windows

#8055 MINIMAL_RUNTIME always uses new event target lookup behavior.
  emcc.py
  tests/test_other.py
Labels: code size

#8048 Fix more scenarios of ENVIRONMENT=web with --closure 1
  src/library.js
  src/library_fs.js
  src/library_sockfs.js
Labels: code size

#8059 Split library_gl.js into library_webgl.js and library_webgl2.js.
  cmake/Modules/FindOpenGL.cmake
  embuilder.py
  site/source/docs/porting/connecting_cpp_and_javascript/Interacting-with-code.rst
  src/library_glemu.js
  src/library_webgl.js
  src/library_webgl2.js
  src/modules.js
  system/include/emscripten/html5.h
  system/lib/gl.symbols
  system/lib/gl/gl.c
  system/lib/gl/webgl1.c
  system/lib/gl/webgl1.h
  system/lib/gl/webgl1_ext.h
  system/lib/gl/webgl2.c
  system/lib/gl/webgl2.h
  tests/test_sanity.py
  tools/shared.py
  tools/system_libs.py
Labels: GL

#8068 webgl2_code_size_comparison
  src/modules.js
  tests/minimal_webgl/webgl.c
  tests/test_other.py
Labels: GL, code size

#8014 Add printf support in MINIMAL_RUNTIME
  emcc.py
  src/deps_info.json
  src/embind/embind.js
  src/library.js
  src/library_fs.js
  src/library_memfs.js
  src/library_syscall.js
  src/library_tty.js
  src/postamble_minimal.js
  tests/test_core.py
Labels: code size, filesystem

#8144 Fix handling of WebGL uniform arrays
  src/library_webgl.js
  tests/test_browser.py
  tests/test_other.py
  tests/webgl_array_of_structs_uniform.c
  tests/webgl_array_of_structs_uniform.png
Labels: GL

#8057 Add support for MODULARIZE=1 with MINIMAL_RUNTIME.
  emcc.py
  src/settings.js
  src/shell_minimal_runtime.html
  tests/test_browser.py
  tests/test_other.py
  tools/hacky_postprocess_around_closure_limitations.py
  tools/separate_asm.py
Labels: code size

#7825 fetch_support_indexeddb
  src/Fetch.js
  src/fetch-worker.js
  src/library_fetch.js
  src/settings.js
  src/struct_info.json
  tests/test_browser.py
  tools/shared.py
Labels: code size
