Repository emscripten-core/emscripten, pull requests merged in 2020-03, with the labels that each got.

#10610 WebGL: Fix memory leak.
  src/library_webgl.js
Labels: GL

#10689 Optimize glUniformMatrix4fv for size and also pthreads+growth by hoisting the heap.
  src/library_webgl.js
Labels: GL, code size

#10702 Fix getBoundingClientRect in touch events
  src/library_html5.js
Labels: HTML5 API

#10703 Fix pthreads in MINIMAL_RUNTIME fastcomp asm.js builds
  src/postamble_minimal.js
Labels: multithreading

#10575 Fix html5 request fullscreen strategy
  src/library_html5.js
Labels: HTML5 API

#10765 Fix pthreads stack alignment in fastcomp pthreads
  emscripten.py
  src/library_pthread.js
Labels: multithreading
