Repository emscripten-core/emscripten, pull requests merged in 2020-08, with the labels that each got.

#11808 Update Khronos headers to latest versions as of 2020-08-04
  system/include/EGL/egl.h
  system/include/EGL/eglext.h
  system/include/EGL/eglplatform.h
  system/include/GL/glext.h
  system/include/GLES/gl.h
  system/include/GLES/glext.h
  system/include/GLES/glplatform.h
  system/include/GLES2/gl2.h
  system/include/GLES2/gl2ext.h
  system/include/GLES2/gl2platform.h
  system/include/GLES3/gl3.h
  system/include/GLES3/gl31.h
  system/include/GLES3/gl32.h
  system/include/GLES3/gl3platform.h
  system/include/KHR/khrplatform.h
Labels: GL

#12012 Refactor emscripten_set_main_loop.
  src/library_browser.js
Labels: code size

#10914 Remove unnecessary restrictions around RTTI from wire.h
  AUTHORS
  ChangeLog.md
  system/include/emscripten/wire.h
  tests/core/test_embind_polymorphic_class_no_rtti.cpp
  tests/core/test_embind_polymorphic_class_no_rtti.out
  tests/test_core.py
Labels: embind

#12047 Improve tests/minimal_webgl for teaching purposes. Improve WebGL validation MIN_WEBGL_VERSION=2 mode.
  src/library_webgl.js
  tests/minimal_webgl/CMakeLists.txt
  tests/minimal_webgl/webgl.c
Labels: GL
