Repository emscripten-core/emscripten, pull requests merged in 2020-02, with the labels that each got.

#10269 Remove PThread.preallocatedWorkers
  src/library_pthread.js
  src/preamble.js
  src/settings.js
  tests/pthread/test_pthread_file_io.cpp
  tests/pthread/test_pthread_preallocates_workers.cpp
Labels: multithreading, performance

#9031 Fix conversion from/to UTF-32
  src/embind/embind.js
Labels: embind

#10123 Minimal runtime pthreads
  emcc.py
  emscripten.py
  src/closure-externs.js
  src/library.js
  src/library_pthread.js
  src/library_syscall.js
  src/memoryprofiler.js
  src/minimal_runtime_worker_externs.js
  src/modules.js
  src/parseTools.js
  src/postamble_minimal.js
  src/preamble.js
  src/preamble_minimal.js
  src/runtime_debug.js
  src/settings_internal.js
  src/shell_minimal.js
  src/shell_minimal_runtime.html
  src/support.js
  src/worker.js
  system/lib/libc/musl/src/thread/pthread_cond_timedwait.c
  tests/pthread/call_async_on_main_thread.js
  tests/pthread/call_sync_on_main_thread.c
  tests/pthread/call_sync_on_main_thread.js
  tests/pthread/test_pthread_mutex.cpp
  tests/pthread/test_pthread_run_script.cpp
  tests/test_browser.py
  tools/minimal_runtime_shell.py
  tools/shared.py
Labels: code size, multithreading
