Repository emscripten-core/emscripten, pull requests merged in 2020-11, with the labels that each got.

#12671 Remove most of the use of modeStringToFlags FS helper
  src/library_fs.js
  src/library_pipefs.js
  src/library_sockfs.js
Labels: code size

#12623 Optimize -s MIN_WEBGL_VERSION=2 and WebGL context creation
  src/library_html5_webgl.js
  src/library_webgl.js
Labels: GL, HTML5 API, code size

#12744 Remove last references to handleFSError
  site/source/api_items.py
  site/source/docs/api_reference/advanced-apis.rst
  src/library.js
Labels: code size

#12784 Fix Windows .bat files
  em++.bat
  em-config.bat
  emar.bat
  embuilder.bat
  emcc.bat
  emcmake.bat
  emconfigure.bat
  emmake.bat
  emranlib.bat
  emrun.bat
  emscons.bat
  emsize.bat
  tools/emdump.bat
  tools/file_packager.bat
  tools/run_python.bat
Labels: windows

#12730 Enable all GL non-debug extensions without maintaining an explicit list of extensions.
  src/library_webgl.js
Labels: GL, code size
