Repository emscripten-core/emscripten, pull requests merged in 2020-07, with the labels that each got.

#11692 Simplify glGetShaderiv slightly
  src/library_webgl.js
Labels: GL

#11742 Repair broken glVertexAttribIPointer in WebGL 2.
  src/library_webgl2.js
Labels: Desktop OpenGL emulation, GL

#11731 Micro-optimize readAsmConstArgs for a 4 byte win.
  src/library.js
Labels: code size
